version: "3.9"

services:
  backend:
    build: .
    ports:
      - "3000:3000" # backend
    volumes:
      - .:/app
    working_dir: /app
    environment:
      # On host run: socat -d -d TCP-LISTEN:54321,reuseaddr,fork FILE:/dev/tty.usbserial-110,raw
      ARDUINO_PORT: socket://host.docker.internal:54321
    tty: true
    stdin_open: true
    command: /app/start.sh

  frontend:
    build: .
    ports:
      - "3001:3001" # shadow-cljs dev server
      - "9630:9630" # nREPL (optional)
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "clojure -M:dev"
